package com.aicfo.domain.engines.stream

import com.aicfo.core.common.Err
import com.aicfo.core.common.Ok
import com.aicfo.core.model.Money
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.LocalDate

/**
 * The golden-file gate for AI-CLS Stage 2 (issue 9.1; §21.5, and the acceptance criteria).
 *
 * Why:  the criterion asks for "a golden-file test on a labelled fixture", and §21.5 asks every
 *       engine for one. Its expectations come from an **independent oracle** (see the file's
 *       header), not from this engine — a golden file generated by the code under test pins
 *       whatever the code does, bugs included, which is the tautology issue 7.4 recorded.
 *       Every record asserts the class **and** the basis **and** every measurement, because a right
 *       class reached by the wrong step is exactly what the known-obligation and pin records exist
 *       to catch.
 * What: runs each record in `golden/streams.txt` through the engine, alone, and compares all eight
 *       outputs.
 * Result: a change to the formula, a threshold or the precedence fails naming the record.
 * Changelog: 2026-09-19 — Created for issue 9.1.
 */
class StreamGoldenTest {
    private val engine = StreamEngineFactory.create()
    private val records: List<GoldenStream> by lazy { load() }

    /**
     * Input:  the golden file.
     * Output: asserts it loaded and still exercises every class and every basis — without this, a
     *         missing resource would make the next test pass over nothing.
     */
    @Test
    fun `the golden file is loaded and exercises every class and every basis`() {
        assertTrue("fewer records than the file documents", records.size >= MIN_RECORDS)
        assertEquals(StreamClass.entries.toSet(), records.map { it.streamClass }.toSet())
        assertEquals(StreamBasis.entries.toSet(), records.map { it.basis }.toSet())
    }

    /** Input: every record. Output: fails listing each record whose verdict differs, and how. */
    @Test
    fun `every stream classifies exactly as the oracle says`() {
        val wrong =
            records.mapNotNull { record ->
                val verdict = classify(record)
                val got =
                    listOf(
                        verdict.streamClass,
                        verdict.basis,
                        verdict.metrics?.render() ?: "-",
                        verdict.typicalMonthly.minor,
                    )
                val want = listOf(record.streamClass, record.basis, record.metrics, record.typical)
                if (got == want) null else "${record.label}: expected $want, got $got"
            }

        assertEquals(wrong.joinToString("\n"), 0, wrong.size)
    }

    // --- helpers ----------------------------------------------------------------------------------

    private fun classify(record: GoldenStream): StreamVerdict {
        val input =
            StreamInput(
                windowStart = WINDOW_START,
                windowEnd = WINDOW_END,
                streams = listOf(record.history),
                nowUtcMillis = NOW,
            )
        return when (val result = engine.classify(input)) {
            is Ok -> result.value.streams.single()
            is Err -> throw AssertionError("${record.label}: ${result.error}")
        }
    }

    private fun StreamMetrics.render() = "$activeMonths/$cvBps/$cadenceBps/$dayLockBps/$scoreBps"

    private fun load(): List<GoldenStream> {
        val text =
            javaClass.classLoader.getResource("golden/streams.txt")?.readText()
                ?: throw AssertionError("golden/streams.txt is missing from the test resources")
        return text.lines().filter { it.isNotBlank() && !it.startsWith("#") }.map(::parse)
    }

    private fun parse(line: String): GoldenStream {
        val f = line.split(" | ").map { it.trim() }
        require(f.size == FIELDS) { "malformed golden record: $line" }
        val occurrences =
            f[8].split(',').map { pair ->
                val (date, paise) = pair.split(':')
                StreamOccurrence(LocalDate.parse(date), Money(paise.toLong()))
            }
        return GoldenStream(
            label = f[0],
            history =
                StreamHistory(
                    streamKey = f[0],
                    priorKey = f[1].takeUnless { it == "-" },
                    occurrences = occurrences,
                    isKnownObligation = f[2] == "yes",
                    pin = f[3].takeUnless { it == "-" }?.let(StreamClass::valueOf),
                ),
            streamClass = StreamClass.valueOf(f[4]),
            basis = StreamBasis.valueOf(f[5]),
            metrics = f[6],
            typical = f[7].toLong(),
        )
    }

    /** One parsed record. */
    private data class GoldenStream(
        val label: String,
        val history: StreamHistory,
        val streamClass: StreamClass,
        val basis: StreamBasis,
        val metrics: String,
        val typical: Long,
    )

    private companion object {
        val WINDOW_START: LocalDate = LocalDate.parse("2026-03-01")
        val WINDOW_END: LocalDate = LocalDate.parse("2026-08-31")
        const val NOW = 1_789_000_000_000L
        const val FIELDS = 9
        const val MIN_RECORDS = 16
    }
}
