#!/usr/bin/env python3
"""
Independent oracle for AI-ORCH's golden file (issue 9.5; §7.2, §21.5).

Why:  the acceptance criterion asks for "a golden-file test on a fixed engine set". The expected
      feed must not come from the engine under test, so this reads the rulebook itself for the
      dashboard size and re-implements RULE-INS-RANK's order from the rule's own words.
What: scores the fixed engine set below — one forecast with crunch days and two seasonal months,
      an emergency fund, a health score, three budgets and two goals — into the ranked feed.
Result: writes insight.txt: one line per insight, in feed order, then the dashboard's fingerprints.
Changelog: 2026-09-20 — Created for issue 9.5.

Order: severity (critical, warning, info), then amount at stake descending (no amount last), then
fingerprint ascending. Fingerprint: type + subject + period, "-" for no subject.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = HERE
while not os.path.isfile(os.path.join(ROOT, "ai/rules/rules-kb.json")):
    ROOT = os.path.dirname(ROOT)
RULES = {r["rule_id"]: r["params_json"] for r in json.load(open(os.path.join(ROOT, "ai/rules/rules-kb.json")))["rules"]}
SEVERITY = RULES["RULE-INS-RANK"]["severity_order"]          # critical, warning, info
DASHBOARD_MAX = RULES["RULE-INS-RANK"]["dashboard_max"]

TYPE_SEVERITY = {
    "CRUNCH_DAY": "critical", "BUDGET_OVERSPENT": "warning", "EMERGENCY_FUND_SHORT": "warning",
    "GOAL_BEHIND": "warning", "SEASONAL_MONTH": "info", "HEALTH_LEVER": "info",
}

# ---- the fixed engine set (mirrored line for line in InsightGoldenTest) -------------------------
FORECAST = dict(crunch_days=2, first="2026-10-05", lowest=320000, buffer=500000,
                seasonal=[("2026-10", 124000), ("2026-11", -60000), ("2026-12", 45000)],
                engine=("AI-FCT", "1.1"), rules=[("RULE-FCT-CRUNCH", "1.0")], confidence=7000)
EMERGENCY = dict(shortfall=12000000, top_up=650000, engine=("AI-EMF", "1.0"),
                 rules=[("RULE-EMF-COACH", "1.0")], confidence=10000)
HEALTH = dict(score=742, lever="SAVINGS_RATE", gain=42, engine=("AI-FHS", "1.0"),
              rules=[("RULE-FHS-PILLARS", "1.0")], confidence=8500)
BUDGETS = [("dining", "Dining", 125000), ("shopping", "Shopping", 1250000), ("fuel", "Fuel", 0)]
GOALS = [("g-laptop", "Laptop", 250000, "2027-03-01"), ("g-trip", "Trip", 0, "2028-01-01")]
MONTH = "2026-09"
TODAY = "2026-09-20"

def insight(kind, subject, label, period, amount, secondary, date, quantity, engine, rules, confidence):
    return dict(type=kind, subject=subject, label=label, period=period, amount=amount,
                secondary=secondary, date=date, quantity=quantity, engine=engine, rules=rules,
                confidence=confidence, fingerprint="%s|%s|%s" % (kind, subject or "-", period))

out = []
if FORECAST["crunch_days"] > 0:
    out.append(insight("CRUNCH_DAY", None, None, TODAY, FORECAST["lowest"], FORECAST["buffer"],
                       FORECAST["first"], FORECAST["crunch_days"], FORECAST["engine"], FORECAST["rules"], FORECAST["confidence"]))
for month, amount in FORECAST["seasonal"]:
    if amount > 0:
        out.append(insight("SEASONAL_MONTH", month, None, month, amount, None, None, None,
                           FORECAST["engine"], FORECAST["rules"], FORECAST["confidence"]))
if EMERGENCY["shortfall"] > 0:
    out.append(insight("EMERGENCY_FUND_SHORT", None, None, TODAY, EMERGENCY["shortfall"], EMERGENCY["top_up"],
                       None, None, EMERGENCY["engine"], EMERGENCY["rules"], EMERGENCY["confidence"]))
if HEALTH["lever"] and HEALTH["gain"]:
    out.append(insight("HEALTH_LEVER", HEALTH["lever"], None, TODAY, None, None, None, HEALTH["gain"],
                       HEALTH["engine"], HEALTH["rules"], HEALTH["confidence"]))
for cid, name, over in BUDGETS:
    if over > 0:
        out.append(insight("BUDGET_OVERSPENT", cid, name, MONTH, over, None, None, None,
                           ("budget-planner", "1.0"), [("RULE-BUD-ALERT", "1.0")], 10000))
for gid, name, short, target in GOALS:
    if short > 0:
        out.append(insight("GOAL_BEHIND", gid, name, target, short, None, None, None,
                           ("AI-GOAL", "1.0"), [("RULE-HORIZON", "1.0")], 9000))

out.sort(key=lambda i: (SEVERITY.index(TYPE_SEVERITY[i["type"]]),
                        0 if i["amount"] is not None else 1,
                        -(i["amount"] or 0),
                        i["fingerprint"]))

lines = ["# AI-ORCH golden file — generated by insight_oracle.py (issue 9.5). Do not edit by hand.",
         "# insight <fingerprint> severity=<s> amount=<paise|-> secondary=<paise|-> date=<iso|-> quantity=<n|-> label=<name|-> engine=<id>/<v> rules=<id v,...> confidence=<bps|->"]
for i in out:
    lines.append("insight %s severity=%s amount=%s secondary=%s date=%s quantity=%s label=%s engine=%s/%s rules=%s confidence=%s" % (
        i["fingerprint"], TYPE_SEVERITY[i["type"]].upper(),
        i["amount"] if i["amount"] is not None else "-",
        i["secondary"] if i["secondary"] is not None else "-",
        i["date"] or "-", i["quantity"] if i["quantity"] is not None else "-", i["label"] or "-",
        i["engine"][0], i["engine"][1],
        ",".join("%s v%s" % r for r in i["rules"]), i["confidence"] if i["confidence"] is not None else "-"))
lines.append("dashboard " + ",".join(i["fingerprint"] for i in out[:DASHBOARD_MAX]))
open(os.path.join(HERE, "insight.txt"), "w").write("\n".join(lines) + "\n")
print("\n".join(lines[2:]))
