// :domain:engines:appliance — §12's closing line, built: "Appliances (Phase 4): same engine,
// different knowledge base (AC service pre-summer, water-purifier filters, extended-warranty
// expiry)." Pure Kotlin (ARC-002). It is handed an appliance, what has been done to it and today's
// date, and answers with dates, rupee ranges and a running cost — never touching a database and
// never reading a clock, so a whole year of an appliance is provable on the JVM against a frozen
// golden file generated by an independent oracle (issue 13.2).
plugins {
    alias(libs.plugins.cfo.kotlin.library)
}

dependencies {
    // api, not implementation: Money and EngineProvenance appear on this engine's public surface,
    // so every caller must be able to name them.
    api(project(":core:model"))
    api(project(":core:common"))

    // Issue 12.1's shared golden-file + seeded-determinism harness. Test-only, so ARC-002 holds.
    testImplementation(testFixtures(project(":core:common")))
}
