#!/usr/bin/env python3
"""
Independent oracle for AI-PA-INT's golden file (issue 10.2; SRS §13.3, §21.5).

Why:  the expected assessments must not come from the engine under test. This reads the rulebook for
      the ladder, the deltas and the outcome bands, and re-applies §13.3 to fixed wishes.
What: one line per wish — band, how many questions are still to ask, the score, the outcome, and
      whether a cooling-off is required.
Changelog: 2026-09-26 — Created for issue 10.2.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = HERE
while not os.path.isfile(os.path.join(ROOT, "ai/rules/rules-kb.json")):
    ROOT = os.path.dirname(ROOT)
RULES = {r["rule_id"]: r["params_json"] for r in json.load(open(os.path.join(ROOT, "ai/rules/rules-kb.json")))["rules"]}
LADDER, SCORE = RULES["RULE-PAI-LADDER"], RULES["RULE-PAI-SCORE"]

# The bank, in the order the ladder asks it. STILL_WANTED is last and never part of a band.
BANK = ["NEED_OR_WANT", "USES_PER_MONTH", "ALREADY_OWN_SIMILAR", "WAIT_THIRTY_DAYS",
        "GOAL_DELAY_ACCEPTABLE", "TOTAL_COST_OF_OWNERSHIP", "TIMING_FLEXIBLE", "COOLING_OFF_ACKNOWLEDGED"]


def band(price, income, method):
    if method == "EMI" and LADDER["emi_is_always_heavy"]:
        return "HEAVY"
    if income <= 0:
        return "HEAVY"
    share = (price * 10000) // income
    for name, key in (("CASUAL", "casual_max_bps"), ("SMALL", "small_max_bps"),
                      ("SIGNIFICANT", "significant_max_bps"), ("MAJOR", "major_max_bps")):
        if share < LADDER[key]:
            return name
    return "HEAVY"


def assess(wish):
    weight = band(wish["price"], wish["income"], wish["method"])
    asked = BANK[: LADDER["questions"][weight.lower()]]
    countable = asked + ["STILL_WANTED"]
    counted = [(q, reason) for q, reason in wish["answers"] if q in countable]
    score = SCORE["start"] + sum(SCORE["deltas"].get(reason, 0) for _, reason in counted)
    outcome = ("KEEP" if score >= SCORE["keep_min"]
               else "PARK" if score >= SCORE["park_min"] else "SUGGEST_REMOVE")
    to_ask = [q for q in asked if q not in [c[0] for c in counted]]
    cooling = "yes" if weight == "HEAVY" else "no"
    return f"wish {wish['name']} {weight} ask={len(to_ask)} score={score} {outcome} cooloff={cooling}"


WISHES = [
    {"name": "coffee_grinder", "price": 400_00, "income": 1_00_000_00, "method": "CASH",
     "answers": [("NEED_OR_WANT", "need")]},
    {"name": "second_headphones", "price": 1_500_00, "income": 1_00_000_00, "method": "CASH",
     "answers": [("NEED_OR_WANT", "want"), ("USES_PER_MONTH", "uses_low"),
                 ("ALREADY_OWN_SIMILAR", "owns_similar")]},
    {"name": "standing_desk", "price": 8_000_00, "income": 1_00_000_00, "method": "CASH",
     "answers": [("NEED_OR_WANT", "need"), ("USES_PER_MONTH", "uses_high"),
                 ("ALREADY_OWN_SIMILAR", "owns_nothing_similar"),
                 ("WAIT_THIRTY_DAYS", "waiting_breaks_something")]},
    {"name": "camera_half_asked", "price": 20_000_00, "income": 1_00_000_00, "method": "CASH",
     "answers": [("NEED_OR_WANT", "want"), ("USES_PER_MONTH", "uses_medium")]},
    {"name": "phone_on_emi", "price": 45_000_00, "income": 1_00_000_00, "method": "EMI",
     "answers": [("NEED_OR_WANT", "need"), ("STILL_WANTED", "still_wanted_after_30_days")]},
]

if __name__ == "__main__":
    print("# AI-PA-INT golden file — generated by interview_oracle.py (issue 10.2). Do not edit by hand.")
    print("# wish <name> <band> ask=<questions still to ask> score=<want score> <outcome> cooloff=<yes|no>")
    for wish in WISHES:
        print(assess(wish))
