package com.aicfo.domain.engines.appliance

import com.aicfo.core.common.GoldenFixture
import com.aicfo.core.common.GoldenRecord
import com.aicfo.core.common.Ok
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The frozen gate for [ApplianceEngine] (issue 13.2; §21.5, AC2, P-08).
 *
 * Why:  AC2 asks for a golden-file test, and the reason this one is worth having is **where the
 *       expected numbers come from**: `appliance_oracle.py` re-implements §12's appliance
 *       prediction in Python, from the same knowledge-base JSON, using Python's own date arithmetic
 *       and `Decimal` rounding. Nothing in the fixture was produced by the engine under test, so a
 *       disagreement means one of the two implementations is wrong and neither can be quietly tuned
 *       to match the other. A golden file generated by the code it checks only pins today's
 *       behaviour; this pins the *specification*.
 * What: eight scenarios covering both due bases and the seasonal edge, a running cost of exactly
 *       zero, a consumable whose clock restarted, and warranties live, expiring and gone.
 * Result: a change to an interval, a tariff, a rounding mode or an alert window cannot land
 *         silently.
 * Changelog: 2026-10-03 — Created for issue 13.2.
 *
 * Uses issue 12.1's shared [GoldenFixture] rather than a reader of its own — which is what refuses
 * to let this test pass over zero records if the fixture is ever emptied or moved.
 */
class ApplianceGoldenTest {
    private val engine = ApplianceEngineFactory.create()

    /**
     * Input:  every record in `golden/appliance.txt`.
     * Output: asserts the whole prediction for each, labelled so a failure names the scenario.
     */
    @Test
    fun `every golden record still holds`() {
        records().forEach { record ->
            val name = record.label()
            val prediction = (engine.predict(inputFrom(record)) as Ok).value

            assertEquals("$name — due date", record.required("expect_due"), prediction.nextService.dueIsoDate)
            assertEquals("$name — basis", record.required("expect_basis"), prediction.nextService.basis.name)
            assertEquals("$name — days away", record.long("expect_days"), prediction.nextService.daysAway)
            assertEquals("$name — cost low", record.long("expect_cost_low"), prediction.predictedCost.low.minor)
            assertEquals("$name — cost high", record.long("expect_cost_high"), prediction.predictedCost.high.minor)
            assertEquals(
                "$name — warranty expiry",
                record.required("expect_warranty"),
                prediction.warranty.expiresOnIsoDate,
            )
            assertEquals("$name — warranty days", record.long("expect_warranty_days"), prediction.warranty.daysAway)
            assertEquals("$name — in warranty", record.boolean("expect_in_warranty"), prediction.warranty.inWarranty)
            assertEquals("$name — running cost", record.long("expect_run"), prediction.runningCostPerMonth.minor)
            assertEquals("$name — consumables", record.required("expect_consumables"), renderConsumables(prediction))
            assertEquals("$name — alerts", record.required("expect_alerts"), renderAlerts(prediction))
        }
    }

    /**
     * Input:  the fixture.
     * Output: asserts it still covers the cases it was built to cover. Eight passing records prove
     *         nothing if seven of them are the same shape — this is what stops the file being
     *         trimmed to the easy ones.
     */
    @Test
    fun `the fixture still covers both due bases, a zero running cost and a dead warranty`() {
        val all = records()
        assertTrue("fewer than eight scenarios — has the fixture been trimmed?", all.size >= EXPECTED_SCENARIOS)

        ApplianceDueBasis.entries.forEach { basis ->
            assertTrue(
                "no golden scenario exercises the $basis due basis",
                all.any { it.required("expect_basis") == basis.name },
            )
        }
        assertTrue("no scenario has a zero running cost", all.any { it.long("expect_run") == 0L })
        assertTrue("no scenario has an expired warranty", all.any { !it.boolean("expect_in_warranty") })
        assertTrue("no scenario has a live warranty", all.any { it.boolean("expect_in_warranty") })
        assertTrue(
            "no scenario raises an overdue consumable",
            all.any { "CONSUMABLE_OVERDUE" in it.required("expect_alerts") },
        )
    }

    // --- building the input ------------------------------------------------------------------------

    /** Result: the engine input a record describes. Input: [record]. Output: [ApplianceInput]. */
    private fun inputFrom(record: GoldenRecord): ApplianceInput =
        ApplianceInput(
            appliance =
                Appliance(
                    id = "appliance:${record.scenario()}",
                    label = record.scenario(),
                    applianceClass = ApplianceClass.valueOf(record.required("class")),
                    purchasedOnIsoDate = record.required("purchased"),
                ),
            todayIsoDate = record.required("today"),
            nowUtcMillis = FIXED_NOW,
            services =
                record.optional("services").orEmpty()
                    .split("|").filter { it.isNotBlank() }
                    .map { ApplianceServiceRecord(it) },
            consumables =
                record.optional("replaced").orEmpty()
                    .split("|").filter { it.isNotBlank() }
                    .map { entry ->
                        val (item, date) = entry.split(":")
                        ConsumableRecord(item, date)
                    },
            usage =
                ApplianceUsage(
                    ratedWatts = record.intOrNull("watts"),
                    minutesPerDay = record.intOrNull("minutes"),
                    tariffPaisePerKwh = record.intOrNull("tariff"),
                ),
        )

    /** Result: the scenario's short name — the first word of the heading. Input: the record. */
    private fun GoldenRecord.scenario(): String = heading.substringBefore(" ")

    /** Result: the consumables as the oracle renders them, or `-`. Input: [prediction]. */
    private fun renderConsumables(prediction: AppliancePrediction): String =
        prediction.consumablesDue
            .joinToString("|") { "${it.item}:${it.due.dueIsoDate}:${it.due.daysAway}" }
            .ifEmpty { "-" }

    /** Result: the alerts as the oracle renders them, or `-`. Input: [prediction]. */
    private fun renderAlerts(prediction: AppliancePrediction): String =
        prediction.alerts
            .joinToString("|") { "${it.kind.name}:${it.daysAway}" }
            .ifEmpty { "-" }

    private fun records(): List<GoldenRecord> = GoldenFixture.load(this, FIXTURE)

    private companion object {
        const val FIXTURE = "/golden/appliance.txt"

        /** Provenance only — the engine reads dates from `todayIsoDate`, never from a clock. */
        const val FIXED_NOW = 1_790_000_000_000L

        /** The scenarios the oracle ships with; a smaller fixture means cases were dropped. */
        const val EXPECTED_SCENARIOS = 8
    }
}
