package com.aicfo.domain.engines.loan

import com.aicfo.core.common.AppError
import com.aicfo.core.common.Result
import com.aicfo.core.model.EngineProvenance
import com.aicfo.core.model.Loan
import com.aicfo.core.model.Money

/**
 * What a loan's numbers mean (issue 6.2; FR-ACC-003, §5.8, §11).
 *
 * Why:  a loan is the one account where the balance tells you almost nothing. "You owe ₹28,40,000"
 *       is true and useless; what a person needs to know is that this month's ₹26,035 is ₹21,250 of
 *       interest and ₹4,785 of principal, and that the ratio inverts somewhere around year fourteen.
 *       That split is also what §8.3 needs to answer "what did this rupee become" for an EMI — the
 *       interest is true spend and the principal is a liability reduction, and ADR-0016 records that
 *       nature classification has been guessing at the account type because nothing could split them.
 *
 *       **Three operations rather than one `analyse()`**, for the reason [com.aicfo.domain.engines]'s
 *       card engine gives: the accounts list wants one instalment and should not build 240 rows to
 *       get it, and the prepay simulator (issue 10.3) wants the EMI and no rows at all.
 * What: one interface, three operations, and the result types they answer with.
 * Result: an instalment and a schedule reproducible from the loan's terms alone (P-08).
 * Changelog: 2026-08-19 — Created for issue 6.2.
 *
 * **No clock, ever** (TIM-001). Instalment dates are generated by adding months to the loan's own
 * `firstEmiIsoDate`; nothing here asks what today is. Reading the wall clock in `:domain:*` fails
 * the build (`CfoWallClockInDomain`), and it is also what makes a twenty-year schedule a golden file.
 *
 * **No `Double` anywhere** (MNY-001/MNY-002): amounts are `Money` paise and the rate is integer
 * basis points. `BigDecimal` appears inside [Emi]'s closed form and never on this surface.
 *
 * **Provenance carries no evidence, and that is deliberate.** `CardStatus` refuses an empty
 * `evidence` list because a card alert is a *judgement* — a threshold fired, and P-02 says the user
 * must be able to see which. Amortisation is not a judgement; it is arithmetic with no tunable in
 * it, and citing a rulebook row it never read would be a false claim about where the number came
 * from. Showing the work here means returning the inputs beside the answer, which every result type
 * below does, and stating the formula in `ENGINE.md`.
 */
interface LoanEngine {
    /**
     * Works out one instalment.
     * Why:    the schedule needs it first, and two callers want it *without* a schedule — the
     *         accounts editor, to show the EMI as the user types the terms, and issue 10.3's
     *         prepay-vs-invest simulator.
     * Result: `Ok(LoanEmi)`, or `Err(AppError.Validation)` when the loan cannot amortise — an
     *         instalment that does not cover the first month's interest never reduces the principal,
     *         and a schedule built from it would run for ever.
     * Input:  [input] — the loan's terms and the provenance stamp.
     * Output: `Result<LoanEmi, AppError>`.
     */
    fun emi(input: LoanTermsInput): Result<LoanEmi, AppError>

    /**
     * Builds the whole amortisation schedule.
     * Why:    the answer to "where does my money actually go", and the thing a golden file can pin
     *         exactly. One row per instalment, in order, first to last.
     * Result: `Ok(AmortisationSchedule)` whose rows' principals sum **exactly** to the loan's
     *         principal, or the same `Err` [emi] returns.
     * Input:  [input]. Output: `Result<AmortisationSchedule, AppError>`.
     */
    fun schedule(input: LoanTermsInput): Result<AmortisationSchedule, AppError>

    /**
     * Works out a single instalment's split without materialising the ones around it.
     * Why:    the accounts list shows the next EMI under every loan. Building 240 rows per row of a
     *         list to read one of them is the kind of waste that only shows up on someone else's
     *         phone. The walk still has to run from instalment 1 — each balance depends on the last
     *         — but nothing is retained.
     * Result: `Ok(AmortisationRow)`, or `Err(AppError.NotFound)` when the number is outside
     *         `1..tenureMonths`: a loan has no eleventh instalment if it runs for ten.
     * Input:  [input] — the terms and which instalment is wanted.
     * Output: `Result<AmortisationRow, AppError>`.
     */
    fun instalment(input: LoanInstalmentInput): Result<AmortisationRow, AppError>
}

/**
 * Where an instalment figure came from (issue 6.2; P-02).
 *
 * Why:  the app shows one EMI, and it is either the closed form applied to the user's terms or the
 *       number their bank actually charges. Those disagree by a rupee or two often enough that a
 *       screen which cannot say which one it is showing invites "your app is wrong". So the basis
 *       travels with the figure, exactly as `UtilisationBasis` travels with a card's ratio.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
enum class EmiBasis {
    /** Computed from principal, rate and tenure by the standard reducing-balance formula. */
    DERIVED,

    /** Entered by the user because their lender charges it. It wins over the derived figure. */
    LENDER_STATED,
}

/**
 * One instalment amount and how it was arrived at (issue 6.2; FR-ACC-003, MNY-001).
 *
 * Input:  [amount] — the monthly instalment in paise; [basis] — [EmiBasis];
 *         [derived] — what the formula produced, carried **even when [basis] is
 *         [EmiBasis.LENDER_STATED]** so the editor can show "your bank charges ₹2 more than the
 *         standard calculation" rather than silently discarding one of the two numbers (P-02);
 *         [provenance] — AI-ARC-003.
 * Output: an immutable value.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
data class LoanEmi(
    val amount: Money,
    val basis: EmiBasis,
    val derived: Money,
    val provenance: EngineProvenance,
)

/**
 * One instalment, split (issue 6.2; FR-ACC-003, §8.3).
 *
 * Why:  the row the whole issue exists to produce. [principal] and [interest] always sum to
 *       [amount] — not approximately, exactly — because the last row absorbs whatever the monthly
 *       roundings left over rather than the schedule pretending they did not happen.
 * Result: what a schedule table renders, and what §8.3's nature split will read once a transaction
 *       can be linked to an instalment.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 *
 * Input:  [number] — which instalment this is, 1-based; [dueIsoDate] — when it falls, ISO
 *         `yyyy-MM-dd` (TIM-002), the loan's first-EMI day clamped to each month's length;
 *         [amount] — what is paid this month, equal to the EMI on every row **except the last**,
 *         which carries the remainder; [principal] — the part that reduces the debt;
 *         [interest] — the part that is the cost of the debt, i.e. true spend (§8.3);
 *         [openingBalance] — what was owed before this instalment; [closingBalance] — after it,
 *         `Money.ZERO` on the final row by construction.
 * Output: an immutable value.
 */
data class AmortisationRow(
    val number: Int,
    val dueIsoDate: String,
    val amount: Money,
    val principal: Money,
    val interest: Money,
    val openingBalance: Money,
    val closingBalance: Money,
) {
    init {
        // Not defensive decoration: this is the acceptance criterion, asserted at the type rather
        // than only in a test, so no future caller can construct a row that does not balance.
        require(principal + interest == amount) {
            "An instalment is its principal plus its interest: ${principal.minor} + ${interest.minor} " +
                "!= ${amount.minor} paise on instalment $number"
        }
        require(openingBalance - principal == closingBalance) {
            "The balance must fall by exactly the principal paid on instalment $number"
        }
    }
}

/**
 * Every instalment of a loan, in order (issue 6.2; FR-ACC-003).
 *
 * Input:  [rows] — one per instalment, first to last; [emi] — the instalment the rows were built
 *         from; [totalInterest] — the cost of the loan over its life, the figure that makes a
 *         tenure decision visible; [provenance] — AI-ARC-003.
 * Output: an immutable value; [rows] is a read-only list.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
data class AmortisationSchedule(
    val rows: List<AmortisationRow>,
    val emi: LoanEmi,
    val totalInterest: Money,
    val provenance: EngineProvenance,
) {
    init {
        require(rows.isNotEmpty()) { "A schedule with no instalments is not a schedule" }
        require(rows.last().closingBalance == Money.ZERO) {
            "A schedule that does not end at zero has not amortised the loan " +
                "(${rows.last().closingBalance.minor} paise left)"
        }
    }
}

/**
 * Input to [LoanEngine.emi] and [LoanEngine.schedule].
 * Input:  [loan] — the terms, already validated by `Loan`'s own `init`;
 *         [nowUtcMillis] — stamped onto provenance only, from the caller's injected `Clock`
 *         (TIM-001); nothing in this engine reads it as a date.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
data class LoanTermsInput(
    val loan: Loan,
    val nowUtcMillis: Long = 0L,
)

/**
 * Input to [LoanEngine.instalment].
 * Input:  [loan]; [number] — which instalment, 1-based; [nowUtcMillis].
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
data class LoanInstalmentInput(
    val loan: Loan,
    val number: Int,
    val nowUtcMillis: Long = 0L,
)

/**
 * Builds the engine for the DI graph (ARC-003).
 * Why:    ARC-003 keeps engine implementations `internal`, so `:app`'s Hilt module cannot name one.
 *         The same seam `CardEngineFactory` and `BudgetEngineFactory` already use.
 * Result: a [LoanEngine]. Input: none. Output: the engine.
 * Changelog: 2026-08-19 — Created for issue 6.2.
 */
object LoanEngineFactory {
    /** Result: the production engine. Input: none. Output: [LoanEngine]. */
    fun create(): LoanEngine = DefaultLoanEngine()
}
