#!/usr/bin/env python3
"""
Independent oracle for AI-NTF's golden file (issue 9.6; §17.2, §21.5).

Why:  the expected decisions must not come from the engine under test. This reads the rulebook
      itself for the caps and the quiet window and re-applies §17.2's rules to a fixed day.
What: one scenario per line of the golden file — a clock reading, a history and a list of
      candidates — with the decision for each candidate.
Changelog: 2026-09-20 — Created for issue 9.6.

Order of questions, as ADR-0047 fixes it: already sent → quiet hours → caps → deliver.
A message held for the quiet hours costs nothing from the ration; a delivered one costs one,
unless it is critical and the rule exempts it.
"""
import json, os
from datetime import datetime, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = HERE
while not os.path.isfile(os.path.join(ROOT, "ai/rules/rules-kb.json")):
    ROOT = os.path.dirname(ROOT)
RULES = {r["rule_id"]: r["params_json"] for r in json.load(open(os.path.join(ROOT, "ai/rules/rules-kb.json")))["rules"]}
CAPS, QUIET = RULES["RULE-NTF-BUDGET"], RULES["RULE-NTF-QUIET"]
CRITICAL_KINDS = {"CRITICAL_MONEY"}

def quiet(now):
    h, start, end = now.hour, QUIET["start_hour"], QUIET["end_hour"]
    return (start <= h < end) if start < end else (h >= start or h < end)

def quiet_end(now):
    end = now.replace(hour=QUIET["end_hour"], minute=0, second=0, microsecond=0)
    return end if end > now else end + timedelta(days=1)

def decide(now, history, candidates):
    sent_keys = {k for (k, _, _) in history}
    today = sum(1 for (_, kind, at) in history if at.date() == now.date() and kind not in CRITICAL_KINDS)
    window = sum(1 for (_, kind, at) in history
                 if at > now - timedelta(days=CAPS["window_days"]) and kind not in CRITICAL_KINDS)
    out = []
    for key, kind in candidates:
        critical = kind in CRITICAL_KINDS
        if key in sent_keys:
            out.append((key, "ALREADY_SENT", "-")); continue
        if not (critical and QUIET["critical_may_bypass"]) and quiet(now):
            out.append((key, "WAIT_FOR_QUIET_HOURS", quiet_end(now).strftime("%Y-%m-%dT%H:%M"))); continue
        if not (critical and CAPS["critical_exempt"]) and (today >= CAPS["daily_max"] or window >= CAPS["weekly_max"]):
            out.append((key, "FOLD_INTO_DIGEST", "-")); continue
        out.append((key, "DELIVER", "-"))
        if not critical:
            today += 1; window += 1
    return out

def dt(text): return datetime.strptime(text, "%Y-%m-%dT%H:%M")

# ---- the fixed scenarios (mirrored line for line in NotificationGoldenTest) ---------------------
SCENARIOS = [
    ("morning_quiet_week", "2026-09-20T09:15",
     [("w1", "BUDGET_DISCIPLINE", "2026-09-15T09:00"), ("w2", "AI_INSIGHT", "2026-09-17T18:00")],
     [("crunch:2026-10-05", "CRITICAL_MONEY"), ("budget:dining", "BUDGET_DISCIPLINE"),
      ("insight:seasonal-2026-10", "AI_INSIGHT"), ("goal:kerala", "GOAL_EVENT")]),
    ("late_evening", "2026-09-20T22:30", [],
     [("crunch:2026-10-05", "CRITICAL_MONEY"), ("budget:dining", "BUDGET_DISCIPLINE")]),
    ("ration_spent", "2026-09-20T11:00",
     [("a", "BUDGET_DISCIPLINE", "2026-09-20T08:10"), ("b", "AI_INSIGHT", "2026-09-20T09:40")],
     [("budget:fuel", "BUDGET_DISCIPLINE"), ("crunch:2026-10-05", "CRITICAL_MONEY")]),
    ("repeat_and_week_full", "2026-09-20T12:00",
     [(k, "AI_INSIGHT", d) for k, d in
      [("w1", "2026-09-14T09:00"), ("w2", "2026-09-15T09:00"), ("w3", "2026-09-16T09:00"),
       ("w4", "2026-09-17T09:00"), ("w5", "2026-09-18T09:00"), ("w6", "2026-09-19T09:00"),
       ("w7", "2026-09-19T13:00"), ("w8", "2026-09-20T09:00")]],
     [("w3", "AI_INSIGHT"), ("insight:lever", "AI_INSIGHT"), ("bill:electricity", "CRITICAL_MONEY")]),
]

lines = ["# AI-NTF golden file — generated by notification_oracle.py (issue 9.6). Do not edit by hand.",
         "# decision <scenario> <key> <outcome> <deliver-after|->"]
for name, now, history, candidates in SCENARIOS:
    parsed = [(k, kind, dt(at)) for (k, kind, at) in history]
    for key, outcome, after in decide(dt(now), parsed, candidates):
        lines.append("decision %s %s %s %s" % (name, key, outcome, after))
open(os.path.join(HERE, "notification.txt"), "w").write("\n".join(lines) + "\n")
print("\n".join(lines[2:]))
