#!/usr/bin/env python3
"""
Independent oracle for AI-CHAT's golden file (issue 10.5; SRS §19.2, §21.5).

Why:  the routing table decides which of the user's data a question reads, and it must not come
      from the engine under test. This re-implements §19's routing from `tool-registry.json` in
      Python — the refusal-first order, the keyword count, the tool cap and the chips — so a
      disagreement means one of the two is wrong.
What: one line per question: the intent it routes to, the tools it would call, the chips offered,
      and the refusal if there is one.
Result: `chat.txt`, which `ChatGoldenTest` compares line for line.
Changelog: 2026-09-26 — Created for issue 10.5.

Run it from anywhere:  python3 chat_oracle.py > chat.txt
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = HERE
while not os.path.isfile(os.path.join(ROOT, "ai/skills/tool-registry.json")):
    ROOT = os.path.dirname(ROOT)
REGISTRY = json.load(open(os.path.join(ROOT, "ai/skills/tool-registry.json")))

INTENTS = REGISTRY["intents"]
ROUTING = REGISTRY["routing"]
OUT_OF_SCOPE = REGISTRY["out_of_scope"]
TOOLS = {t["name"] for t in REGISTRY["tools"]}

# Every intent's tools must exist in the registry, or the routing table points at nothing.
for intent in INTENTS:
    for tool in intent["tools"]:
        assert tool in TOOLS, f"{intent['id']} routes to unknown tool {tool}"


def hits(intent, question):
    """How many of an intent's keywords appear in the question. Input: intent, text. Output: int."""
    return sum(1 for word in intent["keywords"] if word in question)


def plan(text):
    """
    One question's plan, in the order §19 requires: refuse first, then match.
    Input: the user's text. Output: (intent id or '-', [tools], [chips], refusal or '-').
    """
    question = text.strip().lower()
    if not question:
        return ("-", [], [], "VALIDATION")
    if any(word in question for word in OUT_OF_SCOPE["keywords"]):
        return ("-", [], OUT_OF_SCOPE["offer_chips"][: ROUTING["max_chips"]], "OUT_OF_SCOPE")
    matched = [i for i in INTENTS if hits(i, question) >= ROUTING["min_keyword_hits"]]
    if not matched:
        chips = [i["id"] for i in INTENTS[: ROUTING["max_chips"]]]
        return ("-", [], chips, "NOT_UNDERSTOOD")
    # Python's sort is stable, so equal scores keep registry order — the same tie-break the engine
    # gets from `sortedByDescending`.
    ranked = sorted(matched, key=lambda i: hits(i, question), reverse=True)
    best = ranked[0]
    tools = []
    for intent in ranked:
        for tool in intent["tools"]:
            if tool not in tools:
                tools.append(tool)
    return (best["id"], tools[: ROUTING["max_tools_per_turn"]], best["chips"][: ROUTING["max_chips"]], "-")


# Questions chosen so each exercises a different limb: a plain route, a two-intent question that
# hits the cap, a refusal that also looks in scope, a refusal on its own, something unknown, and
# each of the quieter routes.
QUESTIONS = [
    "Where did my money go this month?",
    "What is my balance?",
    "Will I run out of money in the next 90 days?",
    "Am I over budget on dining?",
    "What am I saving for?",
    "Can I afford a phone for 45000?",
    "How am I doing financially?",
    "Should I prepay the loan or invest instead?",
    "What is on my buy list?",
    "When is the car service due?",
    "My budget, my goals, my balance, my score and my spend",
    "Should I buy Reliance today?",
    "Can I afford to file my taxes with a lawyer?",
    "What is the capital of France?",
]

if __name__ == "__main__":
    print("# AI-CHAT golden file — generated by chat_oracle.py (issue 10.5). Do not edit by hand.")
    print("# <question> -> intent=<id> tools=<a|b> chips=<a|b> refusal=<reason>")
    for question in QUESTIONS:
        intent, tools, chips, refusal = plan(question)
        print(f"{question} -> intent={intent} tools={'|'.join(tools) or '-'} "
              f"chips={'|'.join(chips) or '-'} refusal={refusal}")
