package com.aicfo.core.database.crypto

import com.aicfo.core.common.AppError
import com.aicfo.core.common.Err
import com.aicfo.core.common.Ok
import com.aicfo.core.common.Result
import com.aicfo.core.common.flatMap
import com.aicfo.core.common.map
import com.google.crypto.tink.Aead
import java.security.GeneralSecurityException
import java.security.SecureRandom

/**
 * Owns the SQLCipher passphrase: creates it once, keeps it wrapped, hands it back on demand.
 *
 * Why:  SEC-003 (§23) requires the database key to live in the Keystore and never leave the TEE —
 *       but SQLCipher needs actual passphrase bytes in memory to open a file, and a Keystore key
 *       by definition cannot be exported to become those bytes. The sanctioned resolution is
 *       indirection: a random passphrase is generated once, **wrapped** by a Keystore-backed AEAD,
 *       and only the ciphertext touches disk. The key that can unwrap it never leaves the TEE, so
 *       an attacker holding the file and the database still has nothing.
 * What: first-run generation, unwrap on later opens, and rotation. All of it returns
 *       `Result<_, AppError>` — no exception crosses this boundary (§21.6).
 * Result: one passphrase per installation, never written in the clear, never regenerated by
 *       accident.
 * Changelog: 2026-07-25 — Created for issue 1.6 (SEC-003, §23).
 *
 * Deliberately free of Android types: the Keystore lives behind [Aead], which is Tink's own
 * interface. That is what lets the decisions here — the ones that can lose a user's entire
 * database — be unit-tested, leaving a platform binding with no branches in it.
 *
 * **Regenerating instead of failing would be catastrophic.** If the wrapped passphrase cannot be
 * unwrapped (tampering, a cleared Keystore after a factory reset or a lock-screen change), this
 * returns an error. Quietly minting a new passphrase would present an unopenable database as an
 * empty one, and the user would see their finances silently wiped.
 *
 * Input:  [store] — where the wrapped passphrase is persisted; [aead] — the Keystore-backed
 *         wrapper; [random] — a cryptographic source (never a seeded one; P-08's seedable
 *         randomness rule is for engines, and a predictable key would be a vulnerability).
 * Output: passphrase bytes for SQLCipher.
 */
class SqlCipherPassphraseManager(
    private val store: WrappedPassphraseStore,
    private val aead: Aead,
    private val random: SecureRandom,
) {
    /**
     * The passphrase for this installation, creating it on first run.
     * Why:    called on every database open, so it must be idempotent — the second call has to
     *         return exactly what the first one did.
     * Result: `Ok(passphrase)`; `Err(Crypto)` if the stored ciphertext cannot be unwrapped;
     *         `Err(Storage)` if the store itself is unreadable.
     * Input:  none. Output: `Result<ByteArray, AppError>`.
     */
    fun getOrCreate(): Result<ByteArray, AppError> =
        store.read().flatMap { wrapped ->
            if (wrapped == null) createAndStore() else unwrap(wrapped)
        }

    /**
     * Issues a fresh passphrase, replacing the stored one.
     * Why:    SEC-003 asks for a rotation path. The caller must re-key the database with
     *         `PRAGMA rekey` before the old file becomes unreadable, so use
     *         [rotateWithPrevious] unless the database does not exist yet.
     * Result: `Ok(newPassphrase)`, or the wrap/store failure.
     * Input:  none. Output: `Result<ByteArray, AppError>`.
     */
    fun rotate(): Result<ByteArray, AppError> = createAndStore()

    /**
     * Rotates and reports both keys.
     * Why:    re-keying SQLCipher needs the old passphrase to open the file and the new one to
     *         write it back. Handing over only the new key would leave the database openable by
     *         nothing — the failure mode rotation exists to avoid.
     * Result: `Ok(PassphraseChange(previous, current))`; `Err` if there is no existing passphrase
     *         to rotate, because that means the caller is confused about the DB's state.
     * Input:  none. Output: `Result<PassphraseChange, AppError>`.
     */
    fun rotateWithPrevious(): Result<PassphraseChange, AppError> =
        store.read().flatMap { wrapped ->
            when (wrapped) {
                null -> Err(AppError.Crypto("rotate_without_existing_key"))
                else ->
                    unwrap(wrapped).flatMap { previous ->
                        createAndStore().map { current -> PassphraseChange(previous, current) }
                    }
            }
        }

    /**
     * Generates a passphrase, wraps it, and persists the ciphertext.
     * Why:    the order matters — nothing is written until the wrap succeeds, so a Keystore
     *         failure cannot leave a half-initialised store that later reads as corrupt.
     * Result: `Ok(passphrase)` or the first failure encountered.
     * Input:  none. Output: `Result<ByteArray, AppError>`.
     */
    private fun createAndStore(): Result<ByteArray, AppError> {
        val passphrase = ByteArray(PASSPHRASE_BYTES).also(random::nextBytes)
        return wrap(passphrase).flatMap { wrapped ->
            store.write(wrapped).map { passphrase }
        }
    }

    /**
     * Wraps a passphrase with the Keystore-backed AEAD.
     * Result: `Ok(ciphertext)` or `Err(Crypto)` — never a thrown [GeneralSecurityException].
     * Input:  [passphrase] — the raw bytes. Output: `Result<ByteArray, AppError>`.
     */
    private fun wrap(passphrase: ByteArray): Result<ByteArray, AppError> =
        try {
            Ok(aead.encrypt(passphrase, ASSOCIATED_DATA))
        } catch (failure: GeneralSecurityException) {
            Err(AppError.Crypto(failure::class.java.simpleName))
        }

    /**
     * Unwraps the stored ciphertext.
     * Why:    a failure here means the key is gone or the file was tampered with. Both must
     *         surface, never be papered over with a new passphrase (see the class note).
     * Result: `Ok(passphrase)` or `Err(Crypto)`.
     * Input:  [wrapped] — the stored ciphertext. Output: `Result<ByteArray, AppError>`.
     */
    private fun unwrap(wrapped: ByteArray): Result<ByteArray, AppError> =
        try {
            Ok(aead.decrypt(wrapped, ASSOCIATED_DATA))
        } catch (failure: GeneralSecurityException) {
            Err(AppError.Crypto(failure::class.java.simpleName))
        }

    companion object {
        /** 256 bits, matching the AES-256 SQLCipher is configured for. */
        const val PASSPHRASE_BYTES = 32

        /**
         * Binds the ciphertext to this purpose, so a wrapped passphrase cannot be replayed as
         * some other AEAD payload the app stores later.
         */
        @JvmField
        val ASSOCIATED_DATA: ByteArray = "cfo.database.passphrase.v1".toByteArray()
    }
}

/**
 * The two keys a re-key needs.
 * Why:    `PRAGMA rekey` opens with the old passphrase and rewrites with the new one; a type that
 *         carries both makes it impossible to call rotation and forget the old key.
 * Result: a value passed straight to the re-key routine.
 * Input:  [previous] — the passphrase the file is currently encrypted with; [current] — the new one.
 * Output: a data holder.
 * Changelog: 2026-07-25 — Created for issue 1.6.
 */
data class PassphraseChange(
    val previous: ByteArray,
    val current: ByteArray,
) {
    /** Content equality, because these are byte arrays and reference equality would be a bug. */
    override fun equals(other: Any?): Boolean =
        this === other ||
            (
                other is PassphraseChange &&
                    previous.contentEquals(other.previous) &&
                    current.contentEquals(other.current)
            )

    /** Matches [equals]: derived from the array contents, not their identities. */
    override fun hashCode(): Int = 31 * previous.contentHashCode() + current.contentHashCode()
}
