package com.aicfo.core.database.crypto

import com.aicfo.core.common.AppError
import com.aicfo.core.common.Err
import com.aicfo.core.common.Ok
import com.aicfo.core.common.Result
import com.aicfo.core.common.flatMap
import com.aicfo.core.common.map
import com.google.crypto.tink.Aead
import java.security.GeneralSecurityException
import java.security.SecureRandom

/**
 * Owns the SQLCipher passphrase: creates it once, keeps it wrapped, hands it back on demand.
 *
 * Why:  SEC-003 (§23) requires the database key to live in the Keystore and never leave the TEE —
 *       but SQLCipher needs actual passphrase bytes in memory to open a file, and a Keystore key
 *       by definition cannot be exported to become those bytes. The sanctioned resolution is
 *       indirection: a random passphrase is generated once, **wrapped** by a Keystore-backed AEAD,
 *       and only the ciphertext touches disk. The key that can unwrap it never leaves the TEE, so
 *       an attacker holding the file and the database still has nothing.
 * What: first-run generation, unwrap on later opens, and rotation. All of it returns
 *       `Result<_, AppError>` — no exception crosses this boundary (§21.6).
 * Result: one passphrase per installation, never written in the clear, never regenerated by
 *       accident.
 * Changelog: 2026-07-25 — Created for issue 1.6 (SEC-003, §23).
 *
 * Deliberately free of Android types: the Keystore lives behind [Aead], which is Tink's own
 * interface. That is what lets the decisions here — the ones that can lose a user's entire
 * database — be unit-tested, leaving a platform binding with no branches in it.
 *
 * **Regenerating instead of failing would be catastrophic.** If the wrapped passphrase cannot be
 * unwrapped (tampering, a cleared Keystore after a factory reset or a lock-screen change), this
 * returns an error. Quietly minting a new passphrase would present an unopenable database as an
 * empty one, and the user would see their finances silently wiped.
 *
 * Input:  [store] — where the wrapped passphrase is persisted; [aead] — the Keystore-backed
 *         wrapper; [random] — a cryptographic source (never a seeded one; P-08's seedable
 *         randomness rule is for engines, and a predictable key would be a vulnerability).
 * Output: passphrase bytes for SQLCipher.
 */
class SqlCipherPassphraseManager(
    private val store: WrappedPassphraseStore,
    private val aead: Aead,
    private val random: SecureRandom,
) {
    /**
     * The passphrase for this installation, creating it on first run.
     * Why:    called on every database open, so it must be idempotent — the second call has to
     *         return exactly what the first one did.
     * Result: `Ok(passphrase)`; `Err(Crypto)` if the stored ciphertext cannot be unwrapped;
     *         `Err(Storage)` if the store itself is unreadable.
     * Input:  none. Output: `Result<ByteArray, AppError>`.
     */
    fun getOrCreate(): Result<ByteArray, AppError> =
        store.read().flatMap { wrapped ->
            if (wrapped == null) createAndStore() else unwrap(wrapped)
        }

    /**
     * Every passphrase that might open the database right now.
     * Why:    ordinarily there is one. There are two for the length of a rotation, and a process
     *         that dies inside that window leaves the file on one key and the store naming the
     *         other — so the opener is given both and reports back which one worked
     *         ([confirm]). Returning only the current key is what would lose the database.
     * Result: `Ok(PassphraseCandidates)` — creating the first passphrase if there is none;
     *         `Err(Crypto)` if a stored ciphertext will not unwrap; `Err(Storage)` if the store
     *         itself failed.
     * Input:  none. Output: `Result<PassphraseCandidates, AppError>`.
     * Changelog: 2026-09-28 — Created for issue 11.1.
     */
    fun candidates(): Result<PassphraseCandidates, AppError> =
        store.read().flatMap { wrapped ->
            when (wrapped) {
                // A staged key with no current one cannot be a candidate — there is nothing for it
                // to be pending *to*. Only a partial wipe or a half-copied restore reaches this.
                null -> store.clearPending().flatMap { createAndStore() }.map { PassphraseCandidates(it, null) }
                else -> unwrap(wrapped).flatMap { current -> withPending(current) }
            }
        }

    /**
     * Records which candidate actually opened the database.
     * Why:    it is the opener, not this class, that learns whether a rotation took effect — only
     *         the file knows which key it is encrypted with. Promoting the staged key means the
     *         re-key completed; anything else means it did not, and the staged key must go before
     *         it is offered again on a later open.
     * Result: `Ok(Unit)`, or the store's failure.
     * Input:  [opened] — the passphrase the database accepted. Output: `Result<Unit, AppError>`.
     * Changelog: 2026-09-28 — Created for issue 11.1.
     */
    fun confirm(opened: ByteArray): Result<Unit, AppError> =
        store.readPending().flatMap { pending ->
            val staged = pending?.let { unwrap(it).getOrNullOrThrowNothing() }
            if (staged != null && staged.contentEquals(opened)) store.promotePending() else store.clearPending()
        }

    /**
     * Rotates the database key, re-keying the file in the middle of it.
     *
     * Why:    SEC-003 asks for a rotation path, and the order is the whole design. The new key is
     *         staged **before** [rekey] runs and promoted **after** it returns, so every instant
     *         of the operation has both keys on disk. A crash inside the window is recovered by
     *         [candidates]; a failure reported by [rekey] rolls the staging back, because the file
     *         is still on the old key and a staged key that opens nothing would be offered for
     *         ever.
     * What:   unwrap the current key, mint and stage a new one, hand both to [rekey], promote.
     * Result: `Ok(newPassphrase)`; `Err(Crypto)` if there is nothing to rotate — a caller in that
     *         state is confused about whether a database exists, and minting a second key is how
     *         the two slots start disagreeing.
     * Input:  [rekey] — runs `PRAGMA rekey` on the file, given both keys.
     * Output: `Result<ByteArray, AppError>`.
     * Changelog: 2026-09-28 — Created for issue 11.1, replacing a `rotate()` that changed the
     *            stored key without touching the file — which would have locked the user out of
     *            their own database the first time anyone called it.
     */
    fun rotate(rekey: (PassphraseChange) -> Result<Unit, AppError>): Result<ByteArray, AppError> =
        store.read().flatMap { wrapped ->
            when (wrapped) {
                null -> Err(AppError.Crypto("rotate_without_existing_key"))
                else -> unwrap(wrapped).flatMap { previous -> stageAndRekey(previous, rekey) }
            }
        }

    /**
     * The staged half of [rotate].
     * Result: `Ok(newPassphrase)` once promoted; the staging is rolled back on any failure.
     * Input:  [previous] — the key the file is on; [rekey]. Output: `Result<ByteArray, AppError>`.
     * Changelog: 2026-09-28 — Created for issue 11.1.
     */
    private fun stageAndRekey(
        previous: ByteArray,
        rekey: (PassphraseChange) -> Result<Unit, AppError>,
    ): Result<ByteArray, AppError> {
        val current = ByteArray(PASSPHRASE_BYTES).also(random::nextBytes)
        return wrap(current)
            .flatMap { store.writePending(it) }
            .flatMap { rekey(PassphraseChange(previous, current)) }
            .flatMap { store.promotePending().map { current } }
            // The old key is dead the instant the new one is promoted, so it stops existing in
            // this process too. Not a defence against a debugger — SQLCipher holds the live key
            // regardless — but a key that no longer opens anything has no business lingering in a
            // heap dump (security review, issue 11.1).
            .also { outcome -> if (outcome is Ok) previous.fill(0) }
            .recoverBy { failure -> store.clearPending().flatMap { Err(failure) } }
    }

    /**
     * Adds the staged key, when there is one, to the candidates.
     * Result: `Ok(PassphraseCandidates)`. Input: [current]. Output: `Result`.
     * Changelog: 2026-09-28 — Created for issue 11.1.
     */
    private fun withPending(current: ByteArray): Result<PassphraseCandidates, AppError> =
        store.readPending().map { pending ->
            PassphraseCandidates(current, pending?.let { unwrap(it).getOrNullOrThrowNothing() })
        }

    /**
     * Generates a passphrase, wraps it, and persists the ciphertext.
     * Why:    the order matters — nothing is written until the wrap succeeds, so a Keystore
     *         failure cannot leave a half-initialised store that later reads as corrupt.
     * Result: `Ok(passphrase)` or the first failure encountered.
     * Input:  none. Output: `Result<ByteArray, AppError>`.
     */
    private fun createAndStore(): Result<ByteArray, AppError> {
        val passphrase = ByteArray(PASSPHRASE_BYTES).also(random::nextBytes)
        return wrap(passphrase).flatMap { wrapped ->
            store.write(wrapped).map { passphrase }
        }
    }

    /**
     * Wraps a passphrase with the Keystore-backed AEAD.
     * Result: `Ok(ciphertext)` or `Err(Crypto)` — never a thrown [GeneralSecurityException].
     * Input:  [passphrase] — the raw bytes. Output: `Result<ByteArray, AppError>`.
     */
    private fun wrap(passphrase: ByteArray): Result<ByteArray, AppError> =
        try {
            Ok(aead.encrypt(passphrase, ASSOCIATED_DATA))
        } catch (failure: GeneralSecurityException) {
            Err(AppError.Crypto(failure::class.java.simpleName))
        }

    /**
     * Unwraps the stored ciphertext.
     * Why:    a failure here means the key is gone or the file was tampered with. Both must
     *         surface, never be papered over with a new passphrase (see the class note).
     * Result: `Ok(passphrase)` or `Err(Crypto)`.
     * Input:  [wrapped] — the stored ciphertext. Output: `Result<ByteArray, AppError>`.
     */
    private fun unwrap(wrapped: ByteArray): Result<ByteArray, AppError> =
        try {
            Ok(aead.decrypt(wrapped, ASSOCIATED_DATA))
        } catch (failure: GeneralSecurityException) {
            Err(AppError.Crypto(failure::class.java.simpleName))
        }

    companion object {
        /** 256 bits, matching the AES-256 SQLCipher is configured for. */
        const val PASSPHRASE_BYTES = 32

        /**
         * Binds the ciphertext to this purpose, so a wrapped passphrase cannot be replayed as
         * some other AEAD payload the app stores later.
         */
        @JvmField
        val ASSOCIATED_DATA: ByteArray = "cfo.database.passphrase.v1".toByteArray()
    }
}

/**
 * Result: the value, or `null` for an error — used only where a failure means "this candidate
 *         is not usable", never where it means "the database is unreadable".
 * Why:    a staged key that will not unwrap is debris from an interrupted rotation, not a
 *         reason to refuse to open a database the current key opens perfectly well.
 * Input:  the receiver. Output: `T?`.
 * Changelog: 2026-09-28 — Created for issue 11.1.
 */
private fun <T> Result<T, AppError>.getOrNullOrThrowNothing(): T? = (this as? Ok)?.value

/**
 * Runs [fallback] when this result failed, keeping the failure's own error.
 * Why:    the rollback in [stageAndRekey] must run on *every* failure and must not hide it.
 * Result: this result when it succeeded, otherwise [fallback]'s.
 * Input:  [fallback]. Output: `Result<T, AppError>`.
 * Changelog: 2026-09-28 — Created for issue 11.1.
 */
private fun <T> Result<T, AppError>.recoverBy(fallback: (AppError) -> Result<T, AppError>): Result<T, AppError> =
    when (this) {
        is Ok -> this
        is Err -> fallback(error)
    }

/**
 * Every passphrase that might open the database at this moment (issue 11.1).
 *
 * Why:    there are two only while a rotation is in flight or was interrupted, and the opener has
 *         to try them in order rather than assume. A type with a nullable second slot says that
 *         out loud; a list would invite a caller to try them in any order they liked.
 * Result: what `candidates()` returns.
 * Input:  [current] — the promoted key; [pending] — a staged key from an interrupted rotation.
 * Output: an immutable value.
 * Changelog: 2026-09-28 — Created for issue 11.1.
 */
data class PassphraseCandidates(
    val current: ByteArray,
    val pending: ByteArray?,
) {
    /**
     * Zeroes every candidate except [kept].
     * Why:    exactly one of these opened the database; the other opens nothing, now or ever.
     *         Holding it costs nothing and gains nothing, which is the definition of a key that
     *         should be gone (security review, issue 11.1).
     * Result: the other array is filled with zeros. Input: [kept] — the passphrase that worked.
     * Output: none.
     * Changelog: 2026-09-28 — Created for issue 11.1.
     */
    fun discardAllBut(kept: ByteArray) {
        if (current !== kept) current.fill(0)
        if (pending != null && pending !== kept) pending.fill(0)
    }

    /** Content equality: these are byte arrays, and reference equality would be a bug. */
    override fun equals(other: Any?): Boolean =
        this === other ||
            (
                other is PassphraseCandidates &&
                    current.contentEquals(other.current) &&
                    pending.contentEquals(other.pending)
            )

    /** Matches [equals]: derived from the array contents. */
    override fun hashCode(): Int = 31 * current.contentHashCode() + (pending?.contentHashCode() ?: 0)
}

/**
 * The two keys a re-key needs.
 * Why:    `PRAGMA rekey` opens with the old passphrase and rewrites with the new one; a type that
 *         carries both makes it impossible to call rotation and forget the old key.
 * Result: a value passed straight to the re-key routine.
 * Input:  [previous] — the passphrase the file is currently encrypted with; [current] — the new one.
 * Output: a data holder.
 * Changelog: 2026-07-25 — Created for issue 1.6.
 */
data class PassphraseChange(
    val previous: ByteArray,
    val current: ByteArray,
) {
    /** Content equality, because these are byte arrays and reference equality would be a bug. */
    override fun equals(other: Any?): Boolean =
        this === other ||
            (
                other is PassphraseChange &&
                    previous.contentEquals(other.previous) &&
                    current.contentEquals(other.current)
            )

    /** Matches [equals]: derived from the array contents, not their identities. */
    override fun hashCode(): Int = 31 * previous.contentHashCode() + current.contentHashCode()
}
